spring:
  application:
    name: tech-and-solve-reto
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
logging:
  level:
    com.aerolinea: DEBUG

server:
  port: 8080
  servlet:
    context-path: /reto/aerolinea

aerolinea:
  region: us-east-1
  engine: mysql
  username: user
  password: secret
  conection-url: 127.0.0.1
  conection-port: 33060
    
    
  

  