kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: core-archetype-back-java
  labels:
    app: core-archetype-back-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-archetype-back-java
  template:
    metadata:
      name: core-archetype-back-java
      labels:
        app: core-archetype-back-java
    spec:
      containers:
      - name: core-archetype-back-java
        image: 134391437270.dkr.ecr.us-east-1.amazonaws.com/familia/core-archetype-back-java:0.0.1-SNAPSHOT
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}