kind: Service
apiVersion: v1
metadata:
  name: core-archetype-back-java
  labels:
    app: core-archetype-back-java
spec:
  selector:
    app: core-archetype-back-java
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080